### ISSUE TITLE
Access to Pantsbuild.org website timing out from 189.69.170.0/24 (maybe only Brazil?)

### ISSUE THREAD

**Issue by mauronr** [pantsbuild/pantsbuild.org#274]
Hello there,

This is to Pantsbuild website maintainers.

My team hasn't been able to browse https://pantsbuild.org website nor https://static.pantsbuild.org from our office, with all requests timing out consistently. Some in the team can't from home either, but we can access it from other places.

After a quick survey about the IP addresses, apparently, requests coming from network 189.69.170.0/24 are dropped.

We checked with Cloudflare, as the website is behind their service, and they pointed us to the website maintainer.
Maybe there's some blocking rule?

Who should I contact to address this matter?

Best,
-- Mauro

**Comment by benjyw** [comment]
Cloudflare community support site has many reports of Brazilian ISP Vivo blocking certain traffic to Cloudflare. E.g., 

https://community.cloudflare.com/t/site-is-not-accessible-via-some-internet-providers/382528/16
https://community.cloudflare.com/t/problems-with-dns-proxy-on-cloudflare/712947
https://community.cloudflare.com/t/my-customers-cannot-access-my-website-from-a-specific-network-provider/522378
https://community.cloudflare.com/t/problem-of-routes-to-the-ip-of-one-of-the-cf-servers/429427/9

One reason quoted by a user there is: 

“Just to update you, piracy in Brazil is the cause of this. Anatel requests that certain IPs be blocked, because they run services like IPTV and some ISPs, like VIVO, follow this and don’t tell anyone the reason.
It is possible that if your website is not being accessed by VIVO in Brazil, there must be some order from Anatel for such blocking. Vivo is not transparent about this.
You must have been unlucky that Cloudflare provided an IP used for piracy that is on Anatel’s “blocklist”. Which Vivo follows.”

I don't know if that's true, but consensus is that Vivo is blocking some Cloudflare IPs for whatever reason, and Vivo customers should raise it with them, as there is nothing Cloudflare can do on their end.

**Comment by mauronr** [comment]
The issue has gone away. We're able to browse the website from the same IP addresses as before.

**Comment by benjyw** [comment]
That's great! Looks like the Brazilian ISP sorted it out. Thanks for the update.
