### ISSUE TITLE
Proposal: Check-in help-all output for each version, for easier doc regeneration

### ISSUE THREAD

**Issue by huonw** [pantsbuild/pantsbuild.org#29]
As I understand it, all the files in the `docs/reference` and `versioned_docs/*/reference` directories are code-generated from the JSON output of `pants help-all` for the appropriate version. Currently, it seems that JSON output is transient, so, for instance, adjusting the templates and regenerating _all_ the docs seems like it'd require a script that re-runs the `pants help-all` commands and then the `generate.js` script, for each version.

What do you think about committing the help JSON output for each version (since it's the source of truth)? Assuming my understanding is correct, this would unlock a few things:

- easier regeneration of docs
- ability to validate that someone isn't editing the generated markdown files directly in the repo in CI (i.e. catch mistakes where someone tries to fix a typo here)
- potentially, especially with Pants orchestration, no checking-in of the generated markdown files at all (either that, or easier management https://github.com/pantsbuild/pants/discussions/18235)

**Comment by thejcannon** [comment]
I've also thought about shelving the help output somewhere, so maybe it's a good idea? Because the backends (and pants version maybe?) are baked in, it also serves as documentation for what went into the JSON itself, if it ever should be regenerated.

My only hiccups would be the added complexity of the automation (not much though) and storing giant binary blobs in the repo.

**Comment by thejcannon** [comment]
I really can't decide if this is worth it. :unamused:

**Comment by huonw** [comment]
I think it's definitely work it. Neither of those downsides seem very large.

Did you have some thoughts on how we regenerate the docs for changes like #9, if we don't do this?

**Comment by thejcannon** [comment]
> Did you have some thoughts on how we regenerate the docs for changes like https://github.com/pantsbuild/pantsbuild.org/issues/9, if we don't do this?

Same as we do now (-ish) we'd adjust the template to pass more parameters and adjust the React component(s) to accept them, but also gracefully handle if they are missing. So new regenerations have the new change, but old ones without the change "still work".

**Comment by thejcannon** [comment]
> > Did you have some thoughts on how we regenerate the docs for changes like #9, if we don't do this?
> 
> Same as we do now (-ish) we'd adjust the template to pass more parameters and adjust the React component(s) to accept them, but also gracefully handle if they are missing. So new regenerations have the new change, but old ones without the change "still work".

So actually I had a thought...

I wonder if we ought to just dump the JSON in the template, and let the React component take care of all the little things?

It'd make the build times longer (due to parsing a BUNCH of objects) but it'd mean we could easily change things on all branches without having to re-generate older reference docs (which as we're learning [has thorns](https://github.com/pantsbuild/pantsbuild.org/issues/60))

**Comment by huonw** [comment]
I'm not sure I understand what you mean. I _think_ you're suggesting we output a single JSX component call, instead of generating a mix of markdown & JSX, and thus conceptually shifting when "format text" happens... but I'm not sure how that solves #60. Won't the react component be running the 'same' code and thus have the same problem? Thus, I think I'm missing something.

**Comment by thejcannon** [comment]
I thought it was mentioned earlier, but I guess I'm hallucinating (more likely I commented on the wrong issue).

I was thinking about this in the context of #9. 

Otherwise, yeah you got it. It might be we skip mustache altogether and just render a component call, it's JS either way, we just shifted the work to build-time

**Comment by thejcannon** [comment]
And now I'm realizing as well, we really wouldn't need to template much at all...

As some psuedocode...
```js
const scope = '{{name}}';
const helpAll = JSON.parse(require("..."));

<Subsystem info=helpAll[scope] />
```

If there was a way to generate several pages from a single component/page, then we could actually skip all "sync time" generation and just use the help JSON at build time. 🤔
