### ISSUE TITLE
No redirects for unversioned URLs

### ISSUE THREAD

**Issue by huonw** [pantsbuild/pantsbuild.org#5]
From #4:

Redirects of unversioned URLs don't seem to work; is that expected?
- versioned: original: https://www.pantsbuild.org/v2.18/docs/python, new: https://docs.pantsbuild.org/v2.18/docs/python, redirect: https://docs.pantsbuild.org/2.18.x/docs/python/python-overview (shows content ✅ )
- unversioned: original: https://www.pantsbuild.org/v2.18/docs/python, new: https://docs.pantsbuild.org/docs/python, not redirect and shows no content ❌

**Comment by thejcannon** [comment]
This one I don't feel so sure about...

The "unversioned" URLs are simply whatever the latest version is. So on the URL-generation side of things that seems brittle (as our docs evolve, those URLs will be changing). On the client side of things, it would be nice to redirect these just like the others. Also I don't think we'd ever generate these URLs naturally anymore, but they are convenient.

So we could:
1. Drop them on the floor and close this issue. Easiest technologically speaking, but least nice to the user
2. Have them redirect to 2.20.x docs, since thats the last version that the unversioned URLs point to in the current docs site
3. Have them redirect to their relevant pages of the latest docs, or 404 if those pages no longer exist

Then there's the separate question of "should we try and make it easy to generate versionless URLs for sharing?". I'll let that discussion carry forward in a separate issue if anyone feels strongly and wants to file one.

**Comment by huonw** [comment]
I think option 2 is good enough, although I think they're 2.18 docs at the moment (not 2.20).

In particular, there's a wealth of shared links on the internet/slack/etc that we shouldn't break, and having a "snapshot" of redirects that  lands them somewhere vaguely useful seems like the critical part. If people are still clicking on them in 3 years, they can then switch to future versions themselves, but at least haven't hit a fully dead link.

I agree with your point that it's a separate discussion whether we want the new site to support unversioned links. 👍
