### ISSUE TITLE
Consider showing both text docs "Docs" and API docs "Reference" in single sidebar, same as old site

### ISSUE THREAD

**Issue by huonw** [pantsbuild/pantsbuild.org#8]
From #4:

It seems a bit confusing for users to split the long-form text ("Docs") and detailed API descriptions ("Reference") into separate categories as they are: if I'm looking for how to learn something, I'd be hoping that everything I need is easy to find. Alternatives:
   - Include the reference sections in the sidebar for the docs view (maybe with a divider, if that's possible), but still have a direct link to it in the headings. That is, these things could be after "Tutorials - Coming soon"
      <img width="300" alt="image" src="https://github.com/pantsbuild/pantsbuild.org/assets/1203825/bc998b22-39ba-425a-9a5a-d1ff2987d079">
   - If that doesn't work great, just have a link to "Reference" at the end of the Docs sidebar too, and a link to "Docs" in the "Reference" sidebar. (I.e. repeating links from the header, but in the place users might be looking)

**Comment by thejcannon** [comment]
For the record, this was a design decision I made, and not something Docusaurus forces us to do (although it does make maintenance easier).

The reference docs being in the prose docs was mostly a limitation of readme, and when I demos the docs site at a Pants meetup, this was seen as a positive change.

I made a PR to have them cross-links though, since I think that's a good idea.
